#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "common.h"
#include "compiler.h"
#include "memory.h"
#include "scanner.h"

#ifdef DEBUG_PRINT_CODE
#include "debug.h"
#endif

typedef struct
{
    Token current; // The token currently being evaluated for grammar rules.
    Token previous; // The most recently consumed token, used to match values.
    bool hadError; // Tracks if any compilation error occurred during parsing.
    bool panicMode; // Tracks if the parser is actively recovering from an error.
} Parser;

// Enum representing the precedence of Lox's operators. This ordered from lowest to highest,
// making it easier to parse operators of a given precedence or higher.
typedef enum
{
  PREC_NONE,
  PREC_ASSIGNMENT,  // =
  PREC_OR,          // or
  PREC_AND,         // and
  PREC_EQUALITY,    // == !=
  PREC_COMPARISON,  // < > <= >=
  PREC_TERM,        // + -
  PREC_FACTOR,      // * /
  PREC_UNARY,       // ! -
  PREC_CALL,        // . ()
  PREC_PRIMARY
} Precedence;

typedef void (*ParseFn)(bool canAssign);

typedef struct
{
    ParseFn prefix;  // Function pointer to compile an expression starting with this token type when it appears at the beginning of an expression (e.g., unary operators, literals).
    ParseFn infix;  // Function pointer to compile an expression where this token acts as an operator between a left-hand and right-hand operand (e.g., binary operators).
    Precedence precedence; // The numerical priority level assigned to this token type, controlling how tightly it binds to its surrounding operands.
} ParseRule;

// Struct used to indicate the nesting level a particular token being compiled is. This is to support local variables and lexical scoping.
typedef struct
{
    Token name; // Token used to be able to determine which identifier a particular local variable refers to.
    int depth; // 0 => Global scope. 1 => One level of nesting, e.g. Nested within an IF statement which is in global scope.
    bool isCaptured; // Boolean flag that denotes whether a closure captures the local variable.
} Local;

// Struct used to store the meta-data of an upvalue, which is a variable being closed over in a closure.
typedef struct
{
    uint8_t index; // The local variable stack slot offset or the parent function's upvalue array index being tracked.
    bool isLocal; // A boolean flag indicating whether the upvalue points directly to a local variable in the immediate outer scope.
} Upvalue;

// Tracks the compiler's current context (compiling a function/class? compiling the implicit main()?) to enforce valid syntax rules (like 'return' statement limits).
typedef enum
{
    TYPE_FUNCTION, // A standard, user-defined Lox function declared with the 'fun' keyword.
    TYPE_INITIALIZER, // A constructor method for a given class.
    TYPE_METHOD, // A standard, user-defined method within a Lox class.
    TYPE_SCRIPT // The top-level execution context representing the main body of the source file.
} FunctionType;


typedef struct Compiler
{
    struct Compiler* enclosing; // A pointer to the compiler handling the surrounding lexical scope, allowing us to unwind back to the enclosing function.
    ObjFunction* function; // We can assume that all code within a CLox program is in an implicit main() function body. This points to that function
    FunctionType type; // Distinguishes if we are compiling a top-level script, a standard function, a class method, or an initializer.

    Local locals[UINT8_COUNT]; // A flat array tracking all local variables currently in scope during compilation, limited to a maximum of 256 active locals.
                               // These are ordered in the same order in which they are declared in the source code.
    int localCount; // The total number of local variables currently active in the locals array, used as the next available index slot.
    Upvalue upvalues[UINT8_COUNT]; // A flat array tracking upvalues captured by this function closure, limited to a maximum of 256 active upvalues.
    int scopeDepth; // The current nesting level of blocks being compiled, where 0 represents global scope and greater numbers represent deeper local scopes.
} Compiler;

typedef struct ClassCompiler
{
    struct ClassCompiler* enclosing;
    bool hasSuperclass;
} ClassCompiler;

// Parser to on-demand produce byte-code for some given CLox source code. Compiler to track the lexical scoping of the CLox source code.
Parser parser;
Compiler* current = NULL;
ClassCompiler* currentClass = NULL; // The class being compiled.

// The chunk of byte-code currently being generated by the compiler.
Chunk* compilingChunk;

// Get the current chunk being compiled.
static Chunk* currentChunk()
{
    return &current -> function -> chunk;
}

// Prints formatted compilation errors to stderr and flags that the compilation failed.
static void errorAt(Token* token, const char* message)
{
    if (parser.panicMode) return;

    // Error has occurred so enter panic mode and resynchronise.
    parser.panicMode = true;

    // Print the line number where the error occurred.
    fprintf(stderr, "[line %d] Error", token -> line);

    if (token -> type == TOKEN_EOF)
    {
        fprintf(stderr, " at end");
    }
    else if (token -> type == TOKEN_ERROR)
    {
        // Skip printing the token content if it is already a lexical error.
    }
    else
    {
        // Print the characters of the offending token.
        fprintf(stderr, " at '%.*s'", token -> length, token -> start);
    }

    // Print the descriptive error message and update the parser's error state.
    fprintf(stderr, ": %s\n", message);
    parser.hadError = true;
}

// Report an error on the just parsed token.
static void error(const char* message)
{
    errorAt(&parser.previous, message);
}

// Report an error to the user.
static void errorAtCurrent(const char* message)
{
    errorAt(&parser.current, message);
}

// Advances the parser by consuming the next valid token from the lexer.
static void advance()
{
  // Store the current token as the previous token before moving forward.
  parser.previous = parser.current;

  // Loop indefinitely until a valid token (not an error) is encountered.
  for (;;) {
    // Scan the next token from the source code.
    parser.current = scanToken();

    // Exit the loop if the scanned token is a valid language token.
    if (parser.current.type != TOKEN_ERROR) break;

    // Report the compilation error found at the current token position.
    errorAtCurrent(parser.current.start);
  }
}

// Advance if a token has a given type. Otherwise report a syntax error on the current token.
static void consume(TokenType type, const char* message)
{
    if (parser.current.type == type)
    {
        advance();
        return;
    }
    errorAtCurrent(message);
}

// Check that the token to be parsed has a particular type.
static bool check(TokenType type)
{
    return parser.current.type == type;
}

// Return false if a token does not match a given type, otherwise consume it and return true.
static bool match(TokenType type)
{
    if (!check(type)) return false;
    advance();
    return true;
}

// Write one byte worth of byte-code to the current chunk of source code being parsed.
// The data written is either an OP-CODE, operand. Line information is also added for runtime error handling.
static void emitByte(uint8_t byte)
{
    writeChunk(currentChunk(), byte, parser.previous.line);
}

// Utility function to be able to quickly write 2-byte long instructions to the chunk.
static void emitBytes(uint8_t byte1, uint8_t byte2)
{
    emitByte(byte1);
    emitByte(byte2);
}

static void emitLoop(int loopStart)
{
    // Write backward loop jump instruction to chunk
    emitByte(OP_LOOP);

    // Calculate backward jump offset including the 2-byte operand size
    int offset = currentChunk() -> count - loopStart + 2;
    if (offset > UINT16_MAX) error("Loop body too large.");

    // Write the 16-bit offset split across two separate bytes
    emitByte((offset >> 8) & 0xff);
    emitByte(offset & 0xff);
}


static void emitReturn()
{
    // Check if we are returning from a constructor and hence do not need to return a value.
    if (current -> type == TYPE_INITIALIZER)
    {
        emitBytes(OP_GET_LOCAL, 0);
    }
    else
    {
        emitByte(OP_NIL);
    }
    emitByte(OP_RETURN);
}

static uint8_t makeConstant(Value value)
{
    // Write the constant to the constant pool (dynamic-array) and return the index in which it was added.
    int constant = addConstant(currentChunk(), value);

    // Constant pool of a chunk can only have a maximum of 256 entries as the CONSTANT_OP <index> only has 1-byte to represent indices in the constant pool.
    if (constant > UINT8_MAX)
    {
        error("Too many constants in one chunk.");
        return 0;
    }
    return (uint8_t)constant;
}

// Write a constant to the chunk.
static void emitConstant(Value value)
{
    // We write the bytes of the OP-CODE, in this case a constant, and the operand itself to the chunk.
    emitBytes(OP_CONSTANT, makeConstant(value));
}

// Replace dummy jump operand, with the real address once the body of the IF statement has been evaluated.
static void patchJump(int offset)
{
    // -2 to adjust for the byte-code jump offset itself.
    int jump = currentChunk() -> count - offset - 2;

    if (jump > UINT16_MAX)
    {
        error("Too much code to jump over.");
    }

    currentChunk() -> code[offset] = (jump >> 8) & 0xff;
    currentChunk() -> code[offset+1] = jump & 0xff;
}

static int emitJump(uint8_t instruction)
{
    // Write the jump op-code to the chunk
    emitByte(instruction);

    // Write 2 placeholder bytes for the 16-bit jump offset. This enables a maximum jump of 65535 lines of code
    emitByte(0xff);
    emitByte(0xff);

    // Return the starting index of the 2-byte place holder.
    return currentChunk() -> count - 2;
}

static void initCompiler(Compiler* compiler, FunctionType type)
{
    compiler -> enclosing = current;
    compiler -> function = NULL;
    compiler -> type = type;
    compiler -> localCount = 0;
    compiler -> scopeDepth = 0;
    compiler -> function = newFunction();
    current = compiler;
    if (type != TYPE_SCRIPT)
    {
        current -> function -> name = copyString(parser.previous.start, parser.previous.length);
    }

    Local* local = &current -> locals[current -> localCount++];
    local -> depth = 0;
    local -> isCaptured = false;

    if (type != TYPE_FUNCTION)
    {
        local -> name.start = "this";
        local -> name.length = 4;
    }
    else
    {
        local -> name.start = "";
        local -> name.length = 0;
    }
}

// Shut-down procedure for the compiler.
static ObjFunction* endCompiler()
{
    emitReturn();
    // Return the compiled function to the interpreter as the compiler has finished.
    ObjFunction* function = current -> function;
    #ifdef DEBUG_PRINT_CODE
    if (!parser.hadError)
    {
        disassembleChunk(currentChunk(), function -> name != NULL ? function -> name -> chars : "<script>");
    }
    #endif
    current = current -> enclosing;
    return function;
}

// Enter a deeper nested scope, meaning all parsed tokens are in a tighter scope.
static void beginScope()
{
    current -> scopeDepth++;
}

// Exit a deeper scope to a looser one, when parsing CLox source code.
// Making sure to pop all locally declared variables off of the VM stack and in the compiler's local list.
static void endScope()
{
    current -> scopeDepth--;
    // Pop tokens while there are locals and they are in the tighter scope we are leaving.
    while (current -> localCount > 0 && current -> locals[current -> localCount - 1].depth > current -> scopeDepth)
    {
        // If the local variable has been closed over by an inner function declaration, emit an instruction to hoist it to the heap.
        if (current -> locals[current -> localCount - 1].isCaptured)
        {
            emitByte(OP_CLOSE_UPVALUE);
        }
        else
        {
            // Otherwise, emit a fast pop instruction to immediately discard the uncaptured variable from the runtime stack.
            emitByte(OP_POP);
        }
        // Decrement the total local count to systematically remove the variable from the compiler's tracking array.
        current -> localCount--;
    }
}

// Forward declarations of functions
static void expression();
static void statement();
static void declaration();
static ParseRule* getRule(TokenType type);
static void parsePrecedence(Precedence precedence);
static uint8_t identifierConstant(Token* name);
static uint8_t parseVariable(const char* errorMessage);
static void defineVariable(uint8_t global);
static int resolveLocal(Compiler* compiler, Token* name);
static void markInitialized();
static int initJump(uint8_t instruction);
static int resolveUpvalue(Compiler* compiler, Token* name);
static void declareVariable();
static void namedVariable(Token name, bool canAssign);
static void variable(bool canAssign);
static Token syntheticToken(const char* text);
static bool identifiersEqual(Token* a, Token* b);
static void addLocal(Token name);

// Parse a comma-separated list of arguments inside a function call expression.
static uint8_t argumentList()
{
    uint8_t argCount = 0;
    // If the next token is not a closing parenthesis, there are arguments to evaluate.
    if (!check(TOKEN_RIGHT_PAREN))
    {
        do
        {
            // Compile the argument expression, forcing its evaluated value onto the VM stack at runtime.
            expression();
            // Keep a compile-time count of arguments to pass as an operand to the call instruction. Ensuring too many arguments are not given.
            if (argCount == 255)
            {
                error("Can't have more than 255 arguments.");
            }
            argCount++;
        } while (match(TOKEN_COMMA));
    }
    // Ensure the argument list closes cleanly before yielding control back to the call parser.
    consume(TOKEN_RIGHT_PAREN, "Expect ')' after arguments.");
    return argCount;
}


static void and_(bool canAssign)
{
    // Short-circuit: skip the right-hand side if the left operand is false
    int endJump = emitJump(OP_JUMP_IF_FALSE);

    emitByte(OP_POP); // Clean up left operand if it evaluates to true
    parsePrecedence(PREC_AND); // Evaluate the right-hand operand

    // Point the short-circuit jump target here if the left operand was false
    patchJump(endJump);
}

static void binary(bool canAssign)
{
    // Capture the type of the binary operator (e.g., +, -, *, /) that was just consumed.
    TokenType operatorType = parser.previous.type;

    // Look up the matching parsing rule to determine this operator's precedence level.
    ParseRule* rule = getRule(operatorType);

    // Parse the right-hand operand using a higher precedence level (precedence + 1).
    // This enforces left-associativity so that expressions like 'a + b + c' group as '(a + b) + c'
    // rather than letting the right-hand operator tie to 'b' prematurely.
    parsePrecedence((Precedence)(rule->precedence + 1));

    // Emit the appropriate arithmetic byte-code instruction based on the operator type.
    switch (operatorType)
    {
        case TOKEN_BANG_EQUAL: emitBytes(OP_EQUAL, OP_NOT); break;
        case TOKEN_EQUAL_EQUAL: emitByte(OP_EQUAL); break;
        case TOKEN_GREATER: emitByte(OP_GREATER); break;
        case TOKEN_GREATER_EQUAL: emitBytes(OP_LESS, OP_NOT); break;
        case TOKEN_LESS: emitByte(OP_LESS); break;
        case TOKEN_LESS_EQUAL: emitBytes(OP_GREATER, OP_NOT); break;
        case TOKEN_PLUS:  emitByte(OP_ADD); break;
        case TOKEN_MINUS: emitByte(OP_SUBTRACT); break;
        case TOKEN_STAR:  emitByte(OP_MULTIPLY); break;
        case TOKEN_SLASH: emitByte(OP_DIVIDE); break;
        default: return; // Unreachable.
    }
}

// Parse a function call expression, processing its arguments and emitting the call instruction.
static void call(bool canAssign)
{
    // Evaluate the comma-separated arguments on the stack and return the total count.
    uint8_t argCount = argumentList();
    // Emit the call op-code followed by a single-byte operand representing the number of arguments passed.
    emitBytes(OP_CALL, argCount);
}

static void dot(bool canAssign)
{
    // Ensure the token immediately following the dot separator is a valid identifier for the target property.
    consume(TOKEN_IDENTIFIER, "Expect property name after '.'.");
    // Store the property name string literal inside the chunk constant pool and retrieve its index address.
    uint8_t name = identifierConstant(&parser.previous);

    // If the expression context allows mutation and the upcoming token is an assignment operator, process a setter.
    if (canAssign && match(TOKEN_EQUAL))
    {
        // Compile the value expression that will be evaluated and assigned to the object property.
        expression();
        // Emit the property mutation opcode alongside the constant pool slot index tracking the target property name.
        emitBytes(OP_SET_PROPERTY, name);
    }
    else if (match(TOKEN_LEFT_PAREN)) // If a method is accessed and immediately invoked, then short-circuit evaluation for performance.
    {
        uint8_t argCount = argumentList();
        emitBytes(OP_INVOKE, name);
        emitByte(argCount);
    }
    else
    {
        // Emit the property retrieval opcode alongside the constant pool slot index tracking the target property name.
        emitBytes(OP_GET_PROPERTY, name);
    }
}


static void literal(bool canAssign)
{
    // Inspect the specific keyword token type that triggered this prefix compilation routine.
    switch (parser.previous.type)
    {
        // Each literal token type emits a dedicated 1-byte opcode, instructing the VM
        // to push the corresponding immediate built-in value directly onto the stack at runtime.
        case TOKEN_FALSE: emitByte(OP_FALSE); break;
        case TOKEN_NIL:   emitByte(OP_NIL);   break;
        case TOKEN_TRUE:  emitByte(OP_TRUE);  break;
        default: return; // Unreachable.
    }
}

// Parse an expression.
static void expression()
{
    parsePrecedence(PREC_ASSIGNMENT);
}

// Parse a given block statement.
static void block()
{
    // Continue parsing declarations until the closing brace or end of file.
    while (!check(TOKEN_RIGHT_BRACE) && !check(TOKEN_EOF))
    {
        declaration();
    }
    // Consume the closing brace, otherwise runtime a compile error.
    consume(TOKEN_RIGHT_BRACE, "Expect '}' after block.");
}

// Compile a function body and its parameters within a fresh compiler context.
static void function(FunctionType type)
{
    // Initialize a new compiler struct on the C stack, nesting it beneath the current active compiler.
    Compiler compiler;
    initCompiler(&compiler, type);
    beginScope(); // Every function body implicitly introduces a new local scope level for its parameters.

    // Parse the parameter list enclosed in parentheses.
    consume(TOKEN_LEFT_PAREN, "Expect '(' after function name.");
    if(!check(TOKEN_RIGHT_PAREN))
    {
        do
        {
            // Increment the parameter count for the function being compiled.
            current->function->arity++;
            // Byte-code operands use a single byte for indexes, restricting the engine to a hard limit of 255 parameters.
            if (current->function->arity > 255)
            {
                errorAtCurrent("Can't have more than 255 parameters.");
            }
            // Parse the parameter name identifier, injecting it directly into the current scope's local variable array.
            uint8_t constant = parseVariable("Expect parameter name.");
            // Finalize the parameter variable definition, binding its stack slot so it can be accessed inside the body.
            defineVariable(constant);
        } while (match(TOKEN_COMMA));
    }
    consume(TOKEN_RIGHT_PAREN, "Expect ')' after parameters.");

    // Parse the block statement that makes up the executable body of the function.
    consume(TOKEN_LEFT_BRACE, "Expect '{' before function body.");
    block();

    // Terminate compilation for this function, popping its compiler context and returning the finished function object.
    ObjFunction* function = endCompiler();

    // Store the completed function object in the surrounding function's constant table and emit an instruction to load it onto the stack.
    emitBytes(OP_CLOSURE, makeConstant(OBJ_VAL(function)));

    // Create the Byte-code for the closure and the captured up values.
    for (int i = 0; i < function -> upvalueCount; i++)
    {
        emitByte(compiler.upvalues[i].isLocal ? 1 : 0);
        emitByte(compiler.upvalues[i].index);
    }
}

static void method()
{
    // 1. Parse and store the method's name
    consume(TOKEN_IDENTIFIER, "Expect method name.");
    uint8_t constant = identifierConstant(&parser.previous);

    // 2. Compile the method body as an internal function object
    FunctionType type = TYPE_METHOD;
    // Check if the method call is a constructor.
    if (parser.previous.length == 4 && memcmp(parser.previous.start, "init", 4) == 0)
    {
        type = TYPE_INITIALIZER;
    }

    function(type); // Reuses your existing function parameter and block compiler logic

    // 3. Emit the instruction to bind the method function to the class
    emitBytes(OP_METHOD, constant);
}


static void classDeclaration()
{
    consume(TOKEN_IDENTIFIER, "Expect class name.");
    Token className = parser.previous;
    uint8_t nameConstant = identifierConstant(&parser.previous);
    declareVariable();

    emitBytes(OP_CLASS, nameConstant);
    defineVariable(nameConstant);

    ClassCompiler classCompiler;
    classCompiler.hasSuperclass = false; // Initialize this explicitly!
    classCompiler.enclosing = currentClass;
    currentClass = &classCompiler;

    // Inheritance syntax handling
    if (match(TOKEN_LESS))
    {
        consume(TOKEN_IDENTIFIER, "Expect superclass name.");
        variable(false);
        if (identifiersEqual(&className, &parser.previous))
        {
            error("A class can't inherit from itself.");
        }

        // 1. Open the superclass scope ONLY if we have a superclass
        beginScope();
        addLocal(syntheticToken("super"));
        defineVariable(0);
        markInitialized(); // CRUCIAL: Mark "super" as initialized!

        namedVariable(className, false);
        emitByte(OP_INHERIT);
        classCompiler.hasSuperclass = true;
    }

    // 2. Load the class back onto the stack so OP_METHOD can pop it later
    namedVariable(className, false);

    consume(TOKEN_LEFT_BRACE, "Expect '{' before class body.");
    while (!check(TOKEN_RIGHT_BRACE) && !check(TOKEN_EOF))
    {
        method();
    }
    consume(TOKEN_RIGHT_BRACE, "Expect '}' after class body.");

    emitByte(OP_POP); // Pops the class name off the stack

    // 3. Close the superclass scope ONLY if it was opened
    if (classCompiler.hasSuperclass)
    {
        endScope();
    }

    currentClass = currentClass->enclosing;
}

// Parse and compile a function declaration statement.
static void funDeclaration()
{
    // Parse the function name identifier and add it to the global constant table, returning its index.
    uint8_t global = parseVariable("Expect function name.");

    // Mark the function variable as initialized immediately so the function can safely reference itself recursively.
    markInitialized();

    // Compile the function body, parameters, and local byte-code chunk using a separate compiler instance.
    function(TYPE_FUNCTION);

    // Output the byte-code instruction to bind the compiled function object to its identifier in the global table.
    defineVariable(global);
}


static void varDeclaration()
{
    // Parse the variable name being defined, returning the index in the constant pool to be looked up within the VM hash table.
    uint8_t global = parseVariable("Expect variable name.");

    // Check if an initialiser is supplied and if so, evaluate it. Otherwise, assume Nil.
    // Therefore var a; == var a = nil; in the eyes of the compiler.
    if (match(TOKEN_EQUAL))
    {
        expression();
    }
    else
    {
        emitByte(OP_NIL);
    }
    // Consume the semicolon at the end of the declaration.
    consume(TOKEN_SEMICOLON, "Expect ';' after variable declaration.");
    // Define the global variable within
    defineVariable(global);
}

// Parse an expression statement in the normal way.
static void expressionStatement()
{
    expression();
    consume(TOKEN_SEMICOLON, "Expect ';' after expression.");
    emitByte(OP_POP); // Semantically, an expression statement performs a side-effect and we discard the result, therefore issuing a pop from the stack.
}

static void forStatement()
{
    beginScope(); // Enclose the loop variables in their own local scope
    consume(TOKEN_LEFT_PAREN, "Expect '(' after 'for'.");

    // 1. Parse the initializer clause
    if (match(TOKEN_SEMICOLON))
    {
        // No loop initializer.
    }
    else if (match(TOKEN_VAR))
    {
        varDeclaration();
    }
    else
    {
        expressionStatement();
    }

    int loopStart = currentChunk() -> count; // Save point where condition is evaluated
    int exitJump = -1;

    // 2. Parse the condition clause
    if (!match(TOKEN_SEMICOLON))
    {
        expression();
        consume(TOKEN_SEMICOLON, "Expect ';' after loop condition.");

        // Jump out of the loop if the condition is false.
        exitJump = emitJump(OP_JUMP_IF_FALSE); // Changed emitJump to emitJump
        emitByte(OP_POP); // Pop condition result; added missing semicolon
    }

    // 3. Parse the increment clause
    if (!match(TOKEN_RIGHT_PAREN))
    {
        int bodyJump = emitJump(OP_JUMP); // Skip increment code on first pass
        int incrementStart = currentChunk() -> count; // Save point where increment begins
        expression();
        emitByte(OP_POP); // Discard increment expression result
        consume(TOKEN_RIGHT_PAREN, "Expect ')' after for clauses.");

        emitLoop(loopStart); // Loop back to the condition check
        loopStart = incrementStart; // Redirect main loop back to the increment block
        patchJump(bodyJump); // Target for jumping straight into the loop body
    }

    // 4. Parse the loop body
    statement();
    emitLoop(loopStart); // Repeat loop (jumps to increment or condition)

    // Patch the condition's exit jump if one was generated
    if (exitJump != -1)
    {
        patchJump(exitJump);
        emitByte(OP_POP); // Clean up the condition value on exit
    }

    endScope(); // Leave loop's outer local variable scope
}


// Parse an if statement by evaluating its condition and then issuing a jump instruction to perform the control flow.
static void ifStatement()
{
    consume(TOKEN_LEFT_PAREN, "Expect '(' after 'if'.");
    expression(); // Leaves condition result on top of the stack
    consume(TOKEN_RIGHT_PAREN, "Expect ')' after condition.");

    // Emit jump with a placeholder operand; saves index for patching
    int thenJump = emitJump(OP_JUMP_IF_FALSE);
    emitByte(OP_POP); // Clean up condition value if it evaluates to true
    statement(); // Compile the 'then' branch body

    // Track the jump past the else branch; initialized to -1 to signify no else clause is present.
    int elseJump = -1;
    // We must pass over the else clause if the condition is truthy, but only if an else keyword actually exists.
    if (match(TOKEN_ELSE)) {
        elseJump = emitJump(OP_JUMP);
    }

    // Fix the placeholder jump operand to point to the current chunk offset
    patchJump(thenJump);
    emitByte(OP_POP); // Clean up condition value if it evaluates to false

    // Compile the else branch body and patch its jump offset only if one was found during parsing.
    if (elseJump != -1) {
        statement();
        patchJump(elseJump);
    }
}

// Parse a print statement by evaluating the its operand, consuming the semicolon and adding the PRINT op-code to the byte-code chunk.
static void printStatement()
{
    expression();
    consume(TOKEN_SEMICOLON, "Expect ';' after value.");
    emitByte(OP_PRINT);
}

static void returnStatement()
{
    // Ensure that the compiler is within a function, where return statements can be used.
    if (current -> type == TYPE_SCRIPT)
    {
        error("Can't return from top-level code.");
    }

    if (match(TOKEN_SEMICOLON))
    {
        emitReturn();
    }
    else
    {
        if (current -> type == TYPE_INITIALIZER)
        {
            error("Can't return a value from an initializer.");
        }
        expression();
        consume(TOKEN_SEMICOLON, "Expect ';' after return value.");
        emitByte(OP_RETURN);
    }
}

// Parse a while loop statement by evaluating its conditions and issuing jump instructions to implement the control flow.
static void whileStatement()
{
    // Keep a reference to the offset in the chunk that contains the start of the loop, to issue the correct index for the jump.
    int loopStart = currentChunk() -> count;
    consume(TOKEN_LEFT_PAREN, "Expect '(' after 'while'.");
    expression(); // Leaves condition result on top of the stack
    consume(TOKEN_RIGHT_PAREN, "Expect ')' after 'while'.");

    // Skip the loop body if the condition evaluates to false
    int exitJump = emitJump(OP_JUMP_IF_FALSE);
    emitByte(OP_POP); // Clean up condition value if it evaluates to true

    statement(); // Compile the inner loop body statement or block
    emitLoop(loopStart);

    // Fix the placeholder jump operand to point past the loop body
    patchJump(exitJump);
    emitByte(OP_POP); // Clean up condition value if it evaluates to false
}

// Panic Mode synchronisation method, to stop cascading and ghost compilation errors.
static void synchronize()
{
    // The compiler can exit panic mode as it is currently being resolved to a state where the compiler is no longer panicking.
    parser.panicMode = false;

    while (parser.current.type != TOKEN_EOF)
    {
        if (parser.previous.type == TOKEN_SEMICOLON) return;
        switch (parser.current.type)
        {
            case TOKEN_CLASS:
            case TOKEN_FUN:
            case TOKEN_VAR:
            case TOKEN_FOR:
            case TOKEN_IF:
            case TOKEN_WHILE:
            case TOKEN_PRINT:
            case TOKEN_RETURN:
                return;
            default:
                ; // dDo nothing.
        }
    }

    // Advance to ensure the next token is meaningful.
    advance();
}

static void declaration()
{
    if (match(TOKEN_CLASS))
    {
        classDeclaration();
    }
    else if (match(TOKEN_FUN))
    {
        funDeclaration();
    }
    else if (match(TOKEN_VAR))
    {
        varDeclaration();
    }
    else
    {
        statement();
    }
    // Synchronise the compiler if a compile error has been found. This done according to Panic Mode Synchronisation.
    if (parser.panicMode) synchronize();
}

// Parse a given CLox statement into byte-code.
static void statement()
{
    if (match(TOKEN_PRINT))
    {
        printStatement();
    }
    else if (match(TOKEN_FOR))
    {
        forStatement();
    }
    else if (match(TOKEN_IF))
    {
        ifStatement();
    }
    else if (match(TOKEN_RETURN))
    {
        returnStatement();
    }
    else if (match(TOKEN_WHILE))
    {
        whileStatement();
    }
    else if (match(TOKEN_LEFT_BRACE))
    {
        beginScope();
        block();
        endScope();
    }
    else
    {
        expressionStatement();
    }
}

// Parse a parenthesised expression. This simply consumes the brackets and generates the byte-code for the inner expression, because
// it has no runtime-semantics on its own.
static void grouping(bool canAssign)
{
    expression();
    consume(TOKEN_RIGHT_PAREN, "Expect ')' after expression.");
}

// Emit the byte-code for a number literal.
static void number(bool canAssign)
{
    // Convert the token just scanned to a double and write it to the chunk.
    double value = strtod(parser.previous.start, NULL);
    // Wrap the converted number literal into the VM Value type.
    emitConstant(NUMBER_VAL(value));
}

static void or_(bool canAssign)
{
    // If left side is false, skip to evaluating the right side
    int elseJump = emitJump(OP_JUMP_IF_FALSE);
    // If left side is true, jump over the right side completely
    int endJump = emitJump(OP_JUMP);

    // Target for the false-case jump; right side needs evaluation now
    patchJump(elseJump);
    emitByte(OP_POP); // Clean up the left operand value

    parsePrecedence(PREC_OR); // Evaluate the right-hand operand
    patchJump(endJump); // Target for skipping the right side when true
}


// Emit the byte-code for a string literal by stripping its surrounding quotes, copying the characters to the heap, and emitting its constant pool index.
static void string(bool canAssign)
{
    emitConstant(OBJ_VAL(copyString(parser.previous.start + 1, parser.previous.length - 2)));
}

// Compiles variable lookups by adding the name to constants table and emitting byte-code
static void namedVariable(Token name, bool canAssign)
{
    // Store the get and set operations associated with the variable being used.
    uint8_t getOp, setOp;
    // Look for a local variable with this name in the current compiler scopes.
    int arg = resolveLocal(current, &name);

    // If the variable is found in the local scope array (resolveLocal returns an index other than -1),
    // configure the compiler to use stack-based local variable op-codes instead of global ones.
    if (arg != -1)
    {
        getOp = OP_GET_LOCAL;
        setOp = OP_SET_LOCAL;
    }
    else if ((arg = resolveUpvalue(current, &name)) != -1) // Determine if the variable being looked if is an Upvalue and hence used within a closure. Return its index into the closure Upvalue array.
    {
        getOp = OP_GET_UPVALUE;
        setOp = OP_SET_UPVALUE;
    }
    else
    {
        // Otherwise, treat it as a global variable: store the name in the constant table and use global op-codes.
        arg = identifierConstant(&name);
        getOp = OP_GET_GLOBAL;
        setOp = OP_SET_GLOBAL;
    }

    // Emit instruction to fetch the global variable value at that index. If we match an `=` then we know an assignment is taking place and we must evaluate
    // The expression being assigned to, instead of accessing a global variable. On the LHS of the `=`.
    if (canAssign && match(TOKEN_EQUAL))
    {
        expression();
        emitBytes(setOp, (uint8_t)arg);
    }
    else
    {
        emitBytes(getOp, arg);
    }
}

// Pratt parser callback triggered when an identifier is met as an expression
static void variable(bool canAssign)
{
    // Process the identifier token that was just consumed
    namedVariable(parser.previous, canAssign);
}

static Token syntheticToken(const char* text)
{
    Token token;
    token.start = text;
    token.length = (int)strlen(text);
    return token;
}

static void super_(bool canAssign)
{
    if (currentClass == NULL)
    {
        error("Can't use 'super' outside of a class.");
    }
    else if (!currentClass -> hasSuperclass)
    {
        error("Can't use 'super' in a class with no superclass.");
    }

    consume(TOKEN_DOT, "Expect '.' after 'super'.");
    consume(TOKEN_IDENTIFIER, "Expect superclass method name.");
    uint8_t name = identifierConstant(&parser.previous);

    namedVariable(syntheticToken("this"), false);
    if (match(TOKEN_LEFT_PAREN))
    {
        uint8_t argCount = argumentList();
        namedVariable(syntheticToken("super"), false);
        emitBytes(OP_SUPER_INVOKE, name);
        emitByte(argCount);
    }
    else
    {
        namedVariable(syntheticToken("super"), false);
        emitBytes(OP_GET_SUPER, name);
    }
}

// Parse a this expression as a locally defined variable within the class.
static void this_(bool canAssign)
{
    // Can only use this when inside of a class.
    if (currentClass == NULL)
    {
        error("Can't use 'this' outside of a class.");
        return;
    }
    variable(false);
}

// Parse a unary expression (such as !a, -a).
static void unary(bool canAssign)
{
    TokenType operatorType = parser.previous.type;

    // Compile the operand and add it to the chunk of bytecode. We do this before writing the byte-code for the operator due to order of operations.
    // I.e. -a means we need to load a, then negate it and push the result back onto the VM stack.
    parsePrecedence(PREC_UNARY);

    // Emit the operator instruction and add it to the compiled byte-code.
    switch (operatorType)
    {
        case TOKEN_BANG: emitByte(OP_NOT); break;
        case TOKEN_MINUS: emitByte(OP_NEGATE); break;
        default: return; // Unreachable.
    }
}

// A global dispatch table that pairs every distinct token type with its corresponding compilation functions and precedence level.
// We use C's designated array initialiser syntax ('[INDEX] = ...') to explicitly map each 'TokenType' enum value to its exact slot
// within the rules matrix, ensuring clean lookup tracking for the Pratt parser.
ParseRule rules[] = {
  [TOKEN_LEFT_PAREN]    = {grouping, call,   PREC_CALL},   // Starts a grouped expression (e.g., '(1 + 2)'). Has no infix role or intrinsic precedence.
  [TOKEN_RIGHT_PAREN]   = {NULL,     NULL,   PREC_NONE},   // Delimits grouping boundaries. Handled manually inside the grouping function.
  [TOKEN_LEFT_BRACE]    = {NULL,     NULL,   PREC_NONE},   // Delimits block structures. Handled separately by statement parsers.
  [TOKEN_RIGHT_BRACE]   = {NULL,     NULL,   PREC_NONE},   // Delimits block structures. Handled separately by statement parsers.
  [TOKEN_COMMA]         = {NULL,     NULL,   PREC_NONE},   // Delimits arguments and parameters. Evaluated explicitly in call expressions.
  [TOKEN_DOT]           = {NULL,     dot,    PREC_CALL},   // Delimits property access. Will act as an infix operator later.
  [TOKEN_MINUS]         = {unary,    binary, PREC_TERM},   // Dual-role token: acts as prefix negation ('-a') or infix subtraction ('a - b') at addition level.
  [TOKEN_PLUS]          = {NULL,     binary, PREC_TERM},   // Acts strictly as an infix addition operator ('a + b') at the term level.
  [TOKEN_SEMICOLON]     = {NULL,     NULL,   PREC_NONE},   // Statement terminator token. Delimits execution bounds rather than producing values.
  [TOKEN_SLASH]         = {NULL,     binary, PREC_FACTOR}, // Acts strictly as an infix division operator ('a / b') at multiplication level.
  [TOKEN_STAR]          = {NULL,     binary, PREC_FACTOR}, // Acts strictly as an infix multiplication operator ('a * b') at multiplication level.
  [TOKEN_BANG]          = {unary,    NULL,   PREC_NONE},   // Prefix logical negation operator ('!a'). Covered fully in a later section.
  [TOKEN_BANG_EQUAL]    = {NULL,     binary, PREC_EQUALITY},   // Infix structural inequality operator ('a != b'). Covered fully in a later section.
  [TOKEN_EQUAL]         = {NULL,     NULL,   PREC_NONE},   // Variable assignment operator ('a = b'). Evaluated safely below equality levels.
  [TOKEN_EQUAL_EQUAL]   = {NULL,     binary, PREC_EQUALITY},   // Infix structural equality operator ('a == b'). Covered fully in a later section.
  [TOKEN_GREATER]       = {NULL,     binary, PREC_COMPARISON},   // Infix relational comparison operator ('a > b'). Covered fully in a later section.
  [TOKEN_GREATER_EQUAL] = {NULL,     binary, PREC_COMPARISON},   // Infix relational comparison operator ('a >= b'). Covered fully in a later section.
  [TOKEN_LESS]          = {NULL,     binary, PREC_COMPARISON},   // Infix relational comparison operator ('a < b'). Covered fully in a later section.
  [TOKEN_LESS_EQUAL]    = {NULL,     binary, PREC_COMPARISON},   // Infix relational comparison operator ('a <= b'). Covered fully in a later section.
  [TOKEN_IDENTIFIER]    = {variable, NULL,   PREC_NONE},   // Variable lookups and targets. Will act as a prefix literal loader.
  [TOKEN_STRING]        = {string,   NULL,   PREC_NONE},   // Raw character sequence data literal. Will act as a prefix literal loader.
  [TOKEN_NUMBER]        = {number,   NULL,   PREC_NONE},   // Numeric data literal (e.g., '3.14'). Emits raw values immediately via prefix.
  [TOKEN_AND]           = {NULL,     and_,   PREC_AND},    // Logical short-circuiting conjunction operator ('a and b').
  [TOKEN_CLASS]         = {NULL,     NULL,   PREC_NONE},   // Keyword introducing object blueprint descriptions. Handled as a declaration statement.
  [TOKEN_ELSE]          = {NULL,     NULL,   PREC_NONE},   // Keyword splitting conditional statement logical execution flows.
  [TOKEN_FALSE]         = {literal,  NULL,   PREC_NONE},   // Boolean false data literal. Will act as a prefix literal loader.
  [TOKEN_FOR]           = {NULL,     NULL,   PREC_NONE},   // Keyword introducing basic entry iterative control structures.
  [TOKEN_FUN]           = {NULL,     NULL,   PREC_NONE},   // Keyword introducing local subroutine declarations.
  [TOKEN_IF]            = {NULL,     NULL,   PREC_NONE},   // Keyword introducing basic branching conditional execution flows.
  [TOKEN_NIL]           = {literal,  NULL,   PREC_NONE},   // Clear representation of null/empty data references.
  [TOKEN_OR]            = {NULL,     or_,    PREC_NONE},   // Logical short-circuiting disjunction operator ('a or b').
  [TOKEN_PRINT]         = {NULL,     NULL,   PREC_NONE},   // Statement keyword outputting evaluation results straight to stdout.
  [TOKEN_RETURN]        = {NULL,     NULL,   PREC_NONE},   // Statement keyword exiting active frames, optionally tracking output variables.
  [TOKEN_SUPER]         = {super_,   NULL,   PREC_NONE},   // References base implementation contexts during class inheritance lookups.
  [TOKEN_THIS]          = {this_,    NULL,   PREC_NONE},   // References local instantiation contexts during instance method lookups.
  [TOKEN_TRUE]          = {literal,  NULL,   PREC_NONE},   // Boolean true data literal. Will act as a prefix literal loader.
  [TOKEN_VAR]           = {NULL,     NULL,   PREC_NONE},   // Statement keyword declaring new mutable data spaces within local scope.
  [TOKEN_WHILE]         = {NULL,     NULL,   PREC_NONE},   // Keyword introducing basic truth-dependent looping control structures.
  [TOKEN_ERROR]         = {NULL,     NULL,   PREC_NONE},   // Synthetic placeholder token dispatched to signal lexing anomalies safely.
  [TOKEN_EOF]           = {NULL,     NULL,   PREC_NONE},   // Structural sentinel tracking termination of source file instruction scanning.
};

// Parses and compiles expressions at or above a given operator precedence level.
static void parsePrecedence(Precedence precedence)
{
    advance();
     // Retrieve the prefix compilation function pointer associated with the token just consumed.
    ParseFn prefixRule = getRule(parser.previous.type) -> prefix;
    // If the token cannot legally start an expression (no prefix rule exists), flag a compilation error.
    if (prefixRule == NULL)
    {
        error("Expect expression.");
        return;
    }
    // Execute the prefix function to compile the leading component of the expression (e.g., a literal or unary op). Ensuring that precedence with equals is handled properly.
    bool canAssign = precedence <= PREC_ASSIGNMENT;
    prefixRule(canAssign);

    // Keep consuming tokens as long as the incoming operator's precedence meets or exceeds
    // the minimum required precedence parameter level. This binds matching higher-priority operations first.
    while (precedence <= getRule(parser.current.type) -> precedence)
    {
        advance();
        // Fetch the infix compilation function pointer matched to the operator token.
        ParseFn infixRule = getRule(parser.previous.type) -> infix;
        // Execute the infix function (e.g., binary()) to consume the right-hand operand and emit the operation bytecode.
        infixRule(canAssign);
    }

    if (canAssign && match(TOKEN_EQUAL))
    {
        error("Invalid assignment target.");
    }
}

// Adds a variable's name string to the constant pool and returns its index.
static uint8_t identifierConstant(Token* name)
{
    // 1. copyString: Creates a new heap-allocated ObjString from the token text.
    // 2. OBJ_VAL: Wraps that ObjString pointer into a clox Value type.
    // 3. makeConstant: Inserts the Value into the chunk's constant array.
    return makeConstant(OBJ_VAL(copyString(name -> start, name -> length)));
}

// Check that two identifiers are the same.
static bool identifiersEqual(Token* a, Token* b)
{
    if (a -> length != b -> length) return false;
    return memcmp(a -> start, b -> start, a -> length) == 0;
}

// Look up a variable to determine if it is currently in local scope.
static int resolveLocal(Compiler* compiler, Token* name)
{
    // Loop backwards through the locals array to search from the innermost scope outwards.
    // This ensures that variables in inner scopes correctly shadow variables with the same name in outer scopes.
    for (int i = compiler->localCount - 1; i >= 0; i--)
    {
        // Get a pointer to the local variable currently being evaluated in the array.
        Local* local = &compiler->locals[i];

        // Check if the identifier token name matches the name of the tracked local variable.
        if (identifiersEqual(name, &local->name))
        {
            // Ensure that the variable has been fully defined. Return a compiler error if it is not.
            if (local -> depth == -1)
            {
                error("Can't read local variable in its own initializer.");
            }

            // Return the stack slot index where this local variable resides at runtime.
            return i;
        }
    }

    // Return -1 if no local variable with a matching name is found, signaling it may be a global.
    return -1;
}

static int addUpvalue(Compiler* compiler, uint8_t index, bool isLocal)
{
    // Grab the total number of upvalues currently captured by the function being compiled.
    int upvalueCount = compiler -> function -> upvalueCount;

    // Ensure that the upvalue being added, does not already exist. This is so we do not waste time and memory created separate values for each reference.
    for (int i = 0; i < upvalueCount; i++)
    {
        Upvalue* upvalue = &compiler -> upvalues[i];
        if (upvalue -> index == index && upvalue -> isLocal == isLocal)
        {
            return i;
        }
    }

    // Ensure there is enough space to store the upvalue.
    if (upvalueCount == UINT8_COUNT)
    {
        error("Too many closure variables in function.");
        return 0;
    }

    // Store whether the upvalue is a local variable in the direct outer scope, or an inherited upvalue from further out.
    compiler -> upvalues[upvalueCount].isLocal = isLocal;

    // Record the relative stack slot index or the parent function's upvalue array index for this closure tracking.
    compiler -> upvalues[upvalueCount].index = index;

    // Increment the function's internal upvalue tracking counter and return the tracking array slot index for this new upvalue.
    return compiler -> function -> upvalueCount++;
}

static int resolveUpvalue(Compiler* compiler, Token* name)
{
    // If there is no enclosing compiler, we are at the top-level global scope. Therefore, the variable cannot be an upvalue as no closure exists.
    if (compiler -> enclosing == NULL) return -1;

    // Look for the variable within the immediately enclosing function's local variables.
    int local = resolveLocal(compiler -> enclosing, name);
    if (local != -1)
    {
        // If found as a local in the outer scope, capture it as a direct upvalue by setting the `isLocal` flag to true.
        compiler -> enclosing -> locals[local].isCaptured = true;
        return addUpvalue(compiler, (uint8_t)local, true);
    }

    // Recursively add up values to up values in higher scopes to ensure they are always accessible.
    int upvalue = resolveUpvalue(compiler -> enclosing, name);
    if (upvalue != -1)
    {
        return addUpvalue(compiler, (uint8_t)upvalue, false);
    }
    return -1;
}


// Add a local variable to the compilers' locals list. Record the current depth of the compiler to be able to find the correct
// offset within the stack, when accessing the local variable.
static void addLocal(Token name)
{
    // Ensure that we space to define a local variable. As the VM can only keep track of 256 local variables in scope at any one time.
    if (current -> localCount == UINT8_COUNT)
    {
        error("Too many local variables in function.");
        return;
    }

    Local* local = &current -> locals[current -> localCount++];
    local -> name = name;
    // Set depth to -1 to avoid edges cases such as var a = a;
    local -> depth = -1;
    // All locals are assumed to not be captured by a closure.
    local -> isCaptured = false;
}

// Function to declare a local variable. We do not consider globals in the same way as local variables are already stored on the stack,
// and therefore stack offsets can be used to improve performance.
static void declareVariable()
{
    // Global variables are not tracked by the compiler's local array, so exit early if at scope depth 0.
    if (current -> scopeDepth == 0) return;

    // Grab a pointer to the identifier token that was just parsed to use as the variable's name.
    Token* name = &parser.previous;

    // Ensure that a variable cannot be declared with the same name and scope level. Due to creating ambiguity in the compiler.
    // We count backwards because localCount points to the last declared variable. Therefore all previously declared variables are at indices [0..localCount].
    // We can consider all variables currently declared (and therefore have any chance of being in scope) by checking all locals before the one being declared.
    for (int i = current -> localCount - 1; i >= 0; i--)
    {
        Local* local = &current -> locals[i];
        if (local -> depth != -1 && local -> depth < current -> scopeDepth)
        {
            break;
        }

        if (identifiersEqual(name, &local -> name))
        {
            error("Already a variable with this name in this scope.");
        }
    }

    // Append the variable to the compiler's tracking array, marking it as a new local in the current scope.
    addLocal(*name);
}

// Ensures the next token is an identifier and registers its name as a constant.
static uint8_t parseVariable(const char* errorMessage)
{
    consume(TOKEN_IDENTIFIER, errorMessage);

    // Declares the variable to the compiler, tracking it within the locals array if inside a block.
    declareVariable();
    // If the variable is local (scope depth > 0), return a dummy index of 0. Local variables
    // do not store their string names in the constant pool because they are resolved via stack offsets.
    if (current -> scopeDepth > 0)
    {
        markInitialized();
        return 0;
    }


    // Sends the just-consumed identifier token to be stored in the constant pool.
    return identifierConstant(&parser.previous);
}

static void markInitialized()
{
    // Ensure that a function in global scope cannot call this function, as it requires locally scoped variables.
    if (current -> scopeDepth == 0) return;
    current -> locals[current -> localCount - 1].depth = current -> scopeDepth;
}

static void defineVariable(uint8_t global)
{
    if (current -> scopeDepth > 0)
    {
        return;
    }
    emitBytes(OP_DEFINE_GLOBAL, global);
}

// Fetch a parsing rule for the Pratt parser based off of type.
static ParseRule* getRule(TokenType type)
{
    return &rules[type];
}

// Scan and compile Lox source code and produce a chunk of byte-code to be used by the virtual machine.
ObjFunction* compile(const char* source)
{
    initScanner(source);
    Compiler compiler;
    initCompiler(&compiler, TYPE_SCRIPT);

    // Initialise error handling flags.
    parser.hadError = false;
    parser.panicMode = false;

    // Ensure next token is a meaningful one.
    advance();

    while (!match(TOKEN_EOF))
    {
        declaration();
    }

    // We have consumed the EOF token and hence the compiler has produced the required byte-code chunk for the function and can hence be terminated and returned.
    ObjFunction* function = endCompiler();
    return parser.hadError ? NULL : function;
}

void markCompilerRoots()
{
    Compiler* compiler = current;
    while (compiler != NULL)
    {
        markObject((Obj*)compiler -> function);
        compiler = compiler -> enclosing;
    }
}
