#include <stdio.h>
#include <stdlib.h>

#include "common.h"
#include "compiler.h"
#include "scanner.h"

#ifdef DEBUG_PRINT_CODE
#include "debug.h"
#endif

typedef struct
{
    Token current; // The token currently being evaluated for grammar rules.
    Token previous; // The most recently consumed token, used to match values.
    bool hadError; // Tracks if any compilation error occurred during parsing.
    bool panicMode; // Tracks if the parser is actively recovering from an error.
} Parser;

// Enum representing the precedence of Lox's operators. This ordered from lowest to highest,
// making it easier to parse operators of a given precedence or higher.
typedef enum
{
  PREC_NONE,
  PREC_ASSIGNMENT,  // =
  PREC_OR,          // or
  PREC_AND,         // and
  PREC_EQUALITY,    // == !=
  PREC_COMPARISON,  // < > <= >=
  PREC_TERM,        // + -
  PREC_FACTOR,      // * /
  PREC_UNARY,       // ! -
  PREC_CALL,        // . ()
  PREC_PRIMARY
} Precedence;

typedef void (*ParseFn)();

typedef struct
{
    ParseFn prefix;  // Function pointer to compile an expression starting with this token type when it appears at the beginning of an expression (e.g., unary operators, literals).
    ParseFn infix;  // Function pointer to compile an expression where this token acts as an operator between a left-hand and right-hand operand (e.g., binary operators).
    Precedence precedence; // The numerical priority level assigned to this token type, controlling how tightly it binds to its surrounding operands.
} ParseRule;

Parser parser;
// The chunk of byte-code currently being generated by the compiler.
Chunk* compilingChunk;

// Get the current chunk being compiled.
static Chunk* currentChunk()
{
    return compilingChunk;
}

// Prints formatted compilation errors to stderr and flags that the compilation failed.
static void errorAt(Token* token, const char* message)
{
    if (parser.panicMode) return;

    // Error has occurred so enter panic mode and resynchronise.
    parser.panicMode = true;

    // Print the line number where the error occurred.
    fprintf(stderr, "[line %d] Error", token -> line);

    if (token -> type == TOKEN_EOF)
    {
        fprintf(stderr, " at end");
    }
    else if (token -> type == TOKEN_ERROR)
    {
        // Skip printing the token content if it is already a lexical error.
    }
    else
    {
        // Print the characters of the offending token.
        fprintf(stderr, " at '%.*s'", token -> length, token -> start);
    }

    // Print the descriptive error message and update the parser's error state.
    fprintf(stderr, ": %s\n", message);
    parser.hadError = true;
}

// Report an error on the just parsed token.
static void error(const char* message)
{
    errorAt(&parser.previous, message);
}

// Report an error to the user.
static void errorAtCurrent(const char* message)
{
    errorAt(&parser.current, message);
}

// Advances the parser by consuming the next valid token from the lexer.
static void advance() {
  // Store the current token as the previous token before moving forward.
  parser.previous = parser.current;

  // Loop indefinitely until a valid token (not an error) is encountered.
  for (;;) {
    // Scan the next token from the source code.
    parser.current = scanToken();

    // Exit the loop if the scanned token is a valid language token.
    if (parser.current.type != TOKEN_ERROR) break;

    // Report the compilation error found at the current token position.
    errorAtCurrent(parser.current.start);
  }
}

// Advance if a token has a given type. Otherwise report a syntax error on the current token.
static void consume(TokenType type, const char* message)
{
    if (parser.current.type == type)
    {
        advance();
        return;
    }
    errorAtCurrent(message);
}

// Write one byte worth of byte-code to the current chunk of source code being parsed.
// The data written is either an OP-CODE, operand. Line information is also added for runtime error handling.
static void emitByte(uint8_t byte)
{
    writeChunk(currentChunk(), byte, parser.previous.line);
}

// Utility function to be able to quickly write 2-byte long instructions to the chunk.
static void emitBytes(uint8_t byte1, uint8_t byte2)
{
    emitByte(byte1);
    emitByte(byte2);
}

static void emitReturn()
{
    emitByte(OP_RETURN);
}

static uint8_t makeConstant(Value value)
{
    // Write the constant to the constant pool (dynamic-array) and return the index in which it was added.
    int constant = addConstant(currentChunk(), value);

    // Constant pool of a chunk can only have a maximum of 256 entries as the CONSTANT_OP <index> only has 1-byte to represent indices in the constant pool.
    if (constant > UINT8_MAX)
    {
        error("Too many constants in one chunk.");
        return 0;
    }
    return (uint8_t)constant;
}

// Write a constant to the chunk.
static void emitConstant(Value value)
{
    // We write the bytes of the OP-CODE, in this case a constant, and the operand itself to the chunk.
    emitBytes(OP_CONSTANT, makeConstant(value));
}

// Shut-down procedure for the compiler.
static void endCompiler()
{
    emitReturn();
    #ifdef DEBUG_PRINT_CODE
    if (!parser.hadError)
    {
        disassembleChunk(currentChunk(), "code");
    }
    #endif
}

static void expression();
static ParseRule* getRule(TokenType type);
static void parsePrecedence(Precedence precedence);

static void binary()
{
    // Capture the type of the binary operator (e.g., +, -, *, /) that was just consumed.
    TokenType operatorType = parser.previous.type;

    // Look up the matching parsing rule to determine this operator's precedence level.
    ParseRule* rule = getRule(operatorType);

    // Parse the right-hand operand using a higher precedence level (precedence + 1).
    // This enforces left-associativity so that expressions like 'a + b + c' group as '(a + b) + c'
    // rather than letting the right-hand operator tie to 'b' prematurely.
    parsePrecedence((Precedence)(rule->precedence + 1));

    // Emit the appropriate arithmetic byte-code instruction based on the operator type.
    switch (operatorType)
    {
        case TOKEN_BANG_EQUAL: emitBytes(OP_EQUAL, OP_NOT); break;
        case TOKEN_EQUAL_EQUAL: emitByte(OP_EQUAL); break;
        case TOKEN_GREATER: emitByte(OP_GREATER); break;
        case TOKEN_GREATER_EQUAL: emitBytes(OP_LESS, OP_NOT); break;
        case TOKEN_LESS: emitByte(OP_LESS); break;
        case TOKEN_LESS_EQUAL: emitBytes(OP_GREATER, OP_NOT); break;
        case TOKEN_PLUS:  emitByte(OP_ADD); break;
        case TOKEN_MINUS: emitByte(OP_SUBTRACT); break;
        case TOKEN_STAR:  emitByte(OP_MULTIPLY); break;
        case TOKEN_SLASH: emitByte(OP_DIVIDE); break;
        default: return; // Unreachable.
    }
}

static void literal()
{
    // Inspect the specific keyword token type that triggered this prefix compilation routine.
    switch (parser.previous.type)
    {
        // Each literal token type emits a dedicated 1-byte opcode, instructing the VM
        // to push the corresponding immediate built-in value directly onto the stack at runtime.
        case TOKEN_FALSE: emitByte(OP_FALSE); break;
        case TOKEN_NIL:   emitByte(OP_NIL);   break;
        case TOKEN_TRUE:  emitByte(OP_TRUE);  break;
        default: return; // Unreachable.
    }
}

// Parse an expression.
static void expression()
{
    parsePrecedence(PREC_ASSIGNMENT);
}

// Parse a parenthesised expression. This simply consumes the brackets and generates the byte-code for the inner expression, because
// it has no runtime-semantics on its own.
static void grouping()
{
    expression();
    consume(TOKEN_RIGHT_PAREN, "Expect ')' after expression.");
}

// Emit the byte-code for a number literal.
static void number()
{
    // Convert the token just scanned to a double and write it to the chunk.
    double value = strtod(parser.previous.start, NULL);
    // Wrap the converted number literal into the VM Value type.
    emitConstant(NUMBER_VAL(value));
}

// Parse a unary expression (such as !a, -a).
static void unary()
{
    TokenType operatorType = parser.previous.type;

    // Compile the operand and add it to the chunk of bytecode. We do this before writing the byte-code for the operator due to order of operations.
    // I.e. -a means we need to load a, then negate it and push the result back onto the VM stack.
    parsePrecedence(PREC_UNARY);

    // Emit the operator instruction and add it to the compiled byte-code.
    switch (operatorType)
    {
        case TOKEN_BANG: emitByte(OP_NOT); break;
        case TOKEN_MINUS: emitByte(OP_NEGATE); break;
        default: return; // Unreachable.
    }
}

// A global dispatch table that pairs every distinct token type with its corresponding compilation functions and precedence level.
// We use C's designated array initialiser syntax ('[INDEX] = ...') to explicitly map each 'TokenType' enum value to its exact slot
// within the rules matrix, ensuring clean lookup tracking for the Pratt parser.
ParseRule rules[] = {
  [TOKEN_LEFT_PAREN]    = {grouping, NULL,   PREC_NONE},   // Starts a grouped expression (e.g., '(1 + 2)'). Has no infix role or intrinsic precedence.
  [TOKEN_RIGHT_PAREN]   = {NULL,     NULL,   PREC_NONE},   // Delimits grouping boundaries. Handled manually inside the grouping function.
  [TOKEN_LEFT_BRACE]    = {NULL,     NULL,   PREC_NONE},   // Delimits block structures. Handled separately by statement parsers.
  [TOKEN_RIGHT_BRACE]   = {NULL,     NULL,   PREC_NONE},   // Delimits block structures. Handled separately by statement parsers.
  [TOKEN_COMMA]         = {NULL,     NULL,   PREC_NONE},   // Delimits arguments and parameters. Evaluated explicitly in call expressions.
  [TOKEN_DOT]           = {NULL,     NULL,   PREC_NONE},   // Delimits property access. Will act as an infix operator later.
  [TOKEN_MINUS]         = {unary,    binary, PREC_TERM},   // Dual-role token: acts as prefix negation ('-a') or infix subtraction ('a - b') at addition level.
  [TOKEN_PLUS]          = {NULL,     binary, PREC_TERM},   // Acts strictly as an infix addition operator ('a + b') at the term level.
  [TOKEN_SEMICOLON]     = {NULL,     NULL,   PREC_NONE},   // Statement terminator token. Delimits execution bounds rather than producing values.
  [TOKEN_SLASH]         = {NULL,     binary, PREC_FACTOR}, // Acts strictly as an infix division operator ('a / b') at multiplication level.
  [TOKEN_STAR]          = {NULL,     binary, PREC_FACTOR}, // Acts strictly as an infix multiplication operator ('a * b') at multiplication level.
  [TOKEN_BANG]          = {unary,    NULL,   PREC_NONE},   // Prefix logical negation operator ('!a'). Covered fully in a later section.
  [TOKEN_BANG_EQUAL]    = {NULL,     binary, PREC_EQUALITY},   // Infix structural inequality operator ('a != b'). Covered fully in a later section.
  [TOKEN_EQUAL]         = {NULL,     NULL,   PREC_NONE},   // Variable assignment operator ('a = b'). Evaluated safely below equality levels.
  [TOKEN_EQUAL_EQUAL]   = {NULL,     binary, PREC_EQUALITY},   // Infix structural equality operator ('a == b'). Covered fully in a later section.
  [TOKEN_GREATER]       = {NULL,     binary, PREC_COMPARISON},   // Infix relational comparison operator ('a > b'). Covered fully in a later section.
  [TOKEN_GREATER_EQUAL] = {NULL,     binary, PREC_COMPARISON},   // Infix relational comparison operator ('a >= b'). Covered fully in a later section.
  [TOKEN_LESS]          = {NULL,     binary, PREC_COMPARISON},   // Infix relational comparison operator ('a < b'). Covered fully in a later section.
  [TOKEN_LESS_EQUAL]    = {NULL,     binary, PREC_COMPARISON},   // Infix relational comparison operator ('a <= b'). Covered fully in a later section.
  [TOKEN_IDENTIFIER]    = {NULL,     NULL,   PREC_NONE},   // Variable lookups and targets. Will act as a prefix literal loader.
  [TOKEN_STRING]        = {NULL,     NULL,   PREC_NONE},   // Raw character sequence data literal. Will act as a prefix literal loader.
  [TOKEN_NUMBER]        = {number,   NULL,   PREC_NONE},   // Numeric data literal (e.g., '3.14'). Emits raw values immediately via prefix.
  [TOKEN_AND]           = {NULL,     NULL,   PREC_NONE},   // Logical short-circuiting conjunction operator ('a and b').
  [TOKEN_CLASS]         = {NULL,     NULL,   PREC_NONE},   // Keyword introducing object blueprint descriptions. Handled as a declaration statement.
  [TOKEN_ELSE]          = {NULL,     NULL,   PREC_NONE},   // Keyword splitting conditional statement logical execution flows.
  [TOKEN_FALSE]         = {literal,  NULL,   PREC_NONE},   // Boolean false data literal. Will act as a prefix literal loader.
  [TOKEN_FOR]           = {NULL,     NULL,   PREC_NONE},   // Keyword introducing basic entry iterative control structures.
  [TOKEN_FUN]           = {NULL,     NULL,   PREC_NONE},   // Keyword introducing local subroutine declarations.
  [TOKEN_IF]            = {NULL,     NULL,   PREC_NONE},   // Keyword introducing basic branching conditional execution flows.
  [TOKEN_NIL]           = {literal,  NULL,   PREC_NONE},   // Clear representation of null/empty data references.
  [TOKEN_OR]            = {NULL,     NULL,   PREC_NONE},   // Logical short-circuiting disjunction operator ('a or b').
  [TOKEN_PRINT]         = {NULL,     NULL,   PREC_NONE},   // Statement keyword outputting evaluation results straight to stdout.
  [TOKEN_RETURN]        = {NULL,     NULL,   PREC_NONE},   // Statement keyword exiting active frames, optionally tracking output variables.
  [TOKEN_SUPER]         = {NULL,     NULL,   PREC_NONE},   // References base implementation contexts during class inheritance lookups.
  [TOKEN_THIS]          = {NULL,     NULL,   PREC_NONE},   // References local instantiation contexts during instance method lookups.
  [TOKEN_TRUE]          = {literal,  NULL,   PREC_NONE},   // Boolean true data literal. Will act as a prefix literal loader.
  [TOKEN_VAR]           = {NULL,     NULL,   PREC_NONE},   // Statement keyword declaring new mutable data spaces within local scope.
  [TOKEN_WHILE]         = {NULL,     NULL,   PREC_NONE},   // Keyword introducing basic truth-dependent looping control structures.
  [TOKEN_ERROR]         = {NULL,     NULL,   PREC_NONE},   // Synthetic placeholder token dispatched to signal lexing anomalies safely.
  [TOKEN_EOF]           = {NULL,     NULL,   PREC_NONE},   // Structural sentinel tracking termination of source file instruction scanning.
};

// Parses and compiles expressions at or above a given operator precedence level.
static void parsePrecedence(Precedence precedence)
{
    advance();
     // Retrieve the prefix compilation function pointer associated with the token just consumed.
    ParseFn prefixRule = getRule(parser.previous.type) -> prefix;
    // If the token cannot legally start an expression (no prefix rule exists), flag a compilation error.
    if (prefixRule == NULL)
    {
        error("Expect expression.");
        return;
    }
    // Execute the prefix function to compile the leading component of the expression (e.g., a literal or unary op).
    prefixRule();

    // Keep consuming tokens as long as the incoming operator's precedence meets or exceeds
    // the minimum required precedence parameter level. This binds matching higher-priority operations first.
    while (precedence <= getRule(parser.current.type) -> precedence)
    {
        advance();
        // Fetch the infix compilation function pointer matched to the operator token.
        ParseFn infixRule = getRule(parser.previous.type) -> infix;
        // Execute the infix function (e.g., binary()) to consume the right-hand operand and emit the operation bytecode.
        infixRule();
    }
}

// Fetch a parsing rule for the Pratt parser based off of type.
static ParseRule* getRule(TokenType type)
{
    return &rules[type];
}

// Scan and compile Lox source code and produce a chunk of byte-code to be used by the virtual machine.
bool compile(const char* source, Chunk* chunk)
{
    initScanner(source);
    // Chunk to create with the compiler = the chunk within the VM to be filled and is hence empty.
    compilingChunk = chunk;

    // Initialise error handling flags.
    parser.hadError = false;
    parser.panicMode = false;

    // Ensure next token is a meaningful one.
    advance();
    // Parse the expression and consume the end-of-file token.
    expression();
    consume(TOKEN_EOF, "Expect end of expression. ");
    // We have consumed the EOF token and hence the compiler has produced the required byte-code chunk and can hence be terminated.
    endCompiler();
    return !parser.hadError;
}
