#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "common.h"
#include "compiler.h"
#include "scanner.h"

#ifdef DEBUG_PRINT_CODE
#include "debug.h"
#endif

typedef struct
{
    Token current; // The token currently being evaluated for grammar rules.
    Token previous; // The most recently consumed token, used to match values.
    bool hadError; // Tracks if any compilation error occurred during parsing.
    bool panicMode; // Tracks if the parser is actively recovering from an error.
} Parser;

// Enum representing the precedence of Lox's operators. This ordered from lowest to highest,
// making it easier to parse operators of a given precedence or higher.
typedef enum
{
  PREC_NONE,
  PREC_ASSIGNMENT,  // =
  PREC_OR,          // or
  PREC_AND,         // and
  PREC_EQUALITY,    // == !=
  PREC_COMPARISON,  // < > <= >=
  PREC_TERM,        // + -
  PREC_FACTOR,      // * /
  PREC_UNARY,       // ! -
  PREC_CALL,        // . ()
  PREC_PRIMARY
} Precedence;

typedef void (*ParseFn)(bool canAssign);

typedef struct
{
    ParseFn prefix;  // Function pointer to compile an expression starting with this token type when it appears at the beginning of an expression (e.g., unary operators, literals).
    ParseFn infix;  // Function pointer to compile an expression where this token acts as an operator between a left-hand and right-hand operand (e.g., binary operators).
    Precedence precedence; // The numerical priority level assigned to this token type, controlling how tightly it binds to its surrounding operands.
} ParseRule;

// Struct used to indicate the nesting level a particular token being compiled is. This is to support local variables and lexical scoping.
typedef struct
{
    Token name; // Token used to be able to determine which identifier a particular local variable refers to.
    int depth; // 0 => Global scope. 1 => One level of nesting, e.g. Nested within an IF statement which is in global scope.
} Local;

typedef struct
{
    Local locals[UINT8_COUNT]; // A flat array tracking all local variables currently in scope during compilation, limited to a maximum of 256 active locals.
                               // These are ordered in the same order in which they are declared in the source code.
    int localCount; // The total number of local variables currently active in the locals array, used as the next available index slot.
    int scopeDepth; // The current nesting level of blocks being compiled, where 0 represents global scope and greater numbers represent deeper local scopes.
} Compiler;

// Parser to on-demand produce byte-code for some given CLox source code. Compiler to track the lexical scoping of the CLox source code.
Parser parser;
Compiler* current = NULL;

// The chunk of byte-code currently being generated by the compiler.
Chunk* compilingChunk;

// Get the current chunk being compiled.
static Chunk* currentChunk()
{
    return compilingChunk;
}

// Prints formatted compilation errors to stderr and flags that the compilation failed.
static void errorAt(Token* token, const char* message)
{
    if (parser.panicMode) return;

    // Error has occurred so enter panic mode and resynchronise.
    parser.panicMode = true;

    // Print the line number where the error occurred.
    fprintf(stderr, "[line %d] Error", token -> line);

    if (token -> type == TOKEN_EOF)
    {
        fprintf(stderr, " at end");
    }
    else if (token -> type == TOKEN_ERROR)
    {
        // Skip printing the token content if it is already a lexical error.
    }
    else
    {
        // Print the characters of the offending token.
        fprintf(stderr, " at '%.*s'", token -> length, token -> start);
    }

    // Print the descriptive error message and update the parser's error state.
    fprintf(stderr, ": %s\n", message);
    parser.hadError = true;
}

// Report an error on the just parsed token.
static void error(const char* message)
{
    errorAt(&parser.previous, message);
}

// Report an error to the user.
static void errorAtCurrent(const char* message)
{
    errorAt(&parser.current, message);
}

// Advances the parser by consuming the next valid token from the lexer.
static void advance()
{
  // Store the current token as the previous token before moving forward.
  parser.previous = parser.current;

  // Loop indefinitely until a valid token (not an error) is encountered.
  for (;;) {
    // Scan the next token from the source code.
    parser.current = scanToken();

    // Exit the loop if the scanned token is a valid language token.
    if (parser.current.type != TOKEN_ERROR) break;

    // Report the compilation error found at the current token position.
    errorAtCurrent(parser.current.start);
  }
}

// Advance if a token has a given type. Otherwise report a syntax error on the current token.
static void consume(TokenType type, const char* message)
{
    if (parser.current.type == type)
    {
        advance();
        return;
    }
    errorAtCurrent(message);
}

// Check that the token to be parsed has a particular type.
static bool check(TokenType type)
{
    return parser.current.type == type;
}

// Return false if a token does not match a given type, otherwise consume it and return true.
static bool match(TokenType type)
{
    if (!check(type)) return false;
    advance();
    return true;
}

// Write one byte worth of byte-code to the current chunk of source code being parsed.
// The data written is either an OP-CODE, operand. Line information is also added for runtime error handling.
static void emitByte(uint8_t byte)
{
    writeChunk(currentChunk(), byte, parser.previous.line);
}

// Utility function to be able to quickly write 2-byte long instructions to the chunk.
static void emitBytes(uint8_t byte1, uint8_t byte2)
{
    emitByte(byte1);
    emitByte(byte2);
}

static void emitReturn()
{
    emitByte(OP_RETURN);
}

static uint8_t makeConstant(Value value)
{
    // Write the constant to the constant pool (dynamic-array) and return the index in which it was added.
    int constant = addConstant(currentChunk(), value);

    // Constant pool of a chunk can only have a maximum of 256 entries as the CONSTANT_OP <index> only has 1-byte to represent indices in the constant pool.
    if (constant > UINT8_MAX)
    {
        error("Too many constants in one chunk.");
        return 0;
    }
    return (uint8_t)constant;
}

// Write a constant to the chunk.
static void emitConstant(Value value)
{
    // We write the bytes of the OP-CODE, in this case a constant, and the operand itself to the chunk.
    emitBytes(OP_CONSTANT, makeConstant(value));
}

static void initCompiler(Compiler* compiler)
{
    compiler -> localCount = 0;
    compiler -> scopeDepth = 0;
    current = compiler;
}

// Shut-down procedure for the compiler.
static void endCompiler()
{
    emitReturn();
    #ifdef DEBUG_PRINT_CODE
    if (!parser.hadError)
    {
        disassembleChunk(currentChunk(), "code");
    }
    #endif
}

// Enter a deeper nested scope, meaning all parsed tokens are in a tighter scope.
static void beginScope()
{
    current -> scopeDepth++;
}

// Exit a deeper scope to a looser one, when parsing CLox source code.
// Making sure to pop all locally declared variables off of the VM stack and in the compiler's local list.
static void endScope()
{
    current -> scopeDepth--;
    // Pop tokens while there are locals and they are in the tighter scope we are leaving.
    while (current -> localCount > 0 && current -> local[current -> localCount - 1].depth > current -> scopeDepth)
    {
        emitByte(OP_POP);
        current -> localCount--;
    }
}

// Forward declarations of functions
static void expression();
static void statement();
static void declaration();
static ParseRule* getRule(TokenType type);
static void parsePrecedence(Precedence precedence);
static uint8_t identifierConstant(Token* name);
static uint8_t parseVariable(const char* errorMessage);
static void defineVariable(uint8_t global);


static void binary(bool canAssign)
{
    // Capture the type of the binary operator (e.g., +, -, *, /) that was just consumed.
    TokenType operatorType = parser.previous.type;

    // Look up the matching parsing rule to determine this operator's precedence level.
    ParseRule* rule = getRule(operatorType);

    // Parse the right-hand operand using a higher precedence level (precedence + 1).
    // This enforces left-associativity so that expressions like 'a + b + c' group as '(a + b) + c'
    // rather than letting the right-hand operator tie to 'b' prematurely.
    parsePrecedence((Precedence)(rule->precedence + 1));

    // Emit the appropriate arithmetic byte-code instruction based on the operator type.
    switch (operatorType)
    {
        case TOKEN_BANG_EQUAL: emitBytes(OP_EQUAL, OP_NOT); break;
        case TOKEN_EQUAL_EQUAL: emitByte(OP_EQUAL); break;
        case TOKEN_GREATER: emitByte(OP_GREATER); break;
        case TOKEN_GREATER_EQUAL: emitBytes(OP_LESS, OP_NOT); break;
        case TOKEN_LESS: emitByte(OP_LESS); break;
        case TOKEN_LESS_EQUAL: emitBytes(OP_GREATER, OP_NOT); break;
        case TOKEN_PLUS:  emitByte(OP_ADD); break;
        case TOKEN_MINUS: emitByte(OP_SUBTRACT); break;
        case TOKEN_STAR:  emitByte(OP_MULTIPLY); break;
        case TOKEN_SLASH: emitByte(OP_DIVIDE); break;
        default: return; // Unreachable.
    }
}

static void literal(bool canAssign)
{
    // Inspect the specific keyword token type that triggered this prefix compilation routine.
    switch (parser.previous.type)
    {
        // Each literal token type emits a dedicated 1-byte opcode, instructing the VM
        // to push the corresponding immediate built-in value directly onto the stack at runtime.
        case TOKEN_FALSE: emitByte(OP_FALSE); break;
        case TOKEN_NIL:   emitByte(OP_NIL);   break;
        case TOKEN_TRUE:  emitByte(OP_TRUE);  break;
        default: return; // Unreachable.
    }
}

// Parse an expression.
static void expression()
{
    parsePrecedence(PREC_ASSIGNMENT);
}

// Parse a given block statement.
static void block()
{
    // Continue parsing declarations until the closing brace or end of file.
    while (!check(TOKEN_RIGHT_BRACE) && !check(TOKEN_EOF))
    {
        declaration();
    }
    // Consume the closing brace, otherwise runtime a compile error.
    consume(TOKEN_RIGHT_BRACE, "Expect '}' after block.");
}

static void varDeclaration()
{
    // Parse the variable name being defined, returning the index in the constant pool to be looked up within the VM hash table.
    uint8_t global = parseVariable("Expect variable name.");

    // Check if an initialiser is supplied and if so, evaluate it. Otherwise, assume Nil.
    // Therefore var a; == var a = nil; in the eyes of the compiler.
    if (match(TOKEN_EQUAL))
    {
        expression();
    }
    else
    {
        emitByte(OP_NIL);
    }
    // Consume the semicolon at the end of the declaration.
    consume(TOKEN_SEMICOLON, "Expect ';' after variable declaration.");
    // Define the global variable within
    defineVariable(global);
}

// Parse an expression statement in the normal way.
static void expressionStatement()
{
    expression();
    consume(TOKEN_SEMICOLON, "Expect ';' after expression.");
    emitByte(OP_POP); // Semantically, an expression statement performs a side-effect and we discard the result, therefore issuing a pop from the stack.
}

// Parse a print statement by evaluating the its operand, consuming the semicolon and adding the PRINT op-code to the byte-code chunk.
static void printStatement()
{
    expression();
    consume(TOKEN_SEMICOLON, "Expect ';' after value.");
    emitByte(OP_PRINT);
}

// Panic Mode synchronisation method, to stop cascading and ghost compilation errors.
static void synchronize()
{
    // The compiler can exit panic mode as it is currently being resolved to a state where the compiler is no longer panicking.
    parser.panicMode = false;

    while (parser.current.type != TOKEN_EOF)
    {
        if (parser.previous.type == TOKEN_SEMICOLON) return;
        switch (parser.current.type)
        {
            case TOKEN_CLASS:
            case TOKEN_FUN:
            case TOKEN_VAR:
            case TOKEN_FOR:
            case TOKEN_IF:
            case TOKEN_WHILE:
            case TOKEN_PRINT:
            case TOKEN_RETURN:
                return;
            default:
                ; // dDo nothing.
        }
    }

    // Advance to ensure the next token is meaningful.
    advance();
}

static void declaration()
{
    if (match(TOKEN_VAR))
    {
        varDeclaration();
    }
    else
    {
        statement();
    }
    // Synchronise the compiler if a compile error has been found. This done according to Panic Mode Synchronisation.
    if (parser.panicMode) synchronize();
}

// Parse a given CLox statement into byte-code.
static void statement()
{
    if (match(TOKEN_PRINT))
    {
        printStatement();
    }
    else if (match(TOKEN_LEFT_BRACE))
    {
        beginScope();
        block();
        endScope();
    }
    else
    {
        expressionStatement();
    }
}

// Parse a parenthesised expression. This simply consumes the brackets and generates the byte-code for the inner expression, because
// it has no runtime-semantics on its own.
static void grouping(bool canAssign)
{
    expression();
    consume(TOKEN_RIGHT_PAREN, "Expect ')' after expression.");
}

// Emit the byte-code for a number literal.
static void number(bool canAssign)
{
    // Convert the token just scanned to a double and write it to the chunk.
    double value = strtod(parser.previous.start, NULL);
    // Wrap the converted number literal into the VM Value type.
    emitConstant(NUMBER_VAL(value));
}

// Emit the byte-code for a string literal by stripping its surrounding quotes, copying the characters to the heap, and emitting its constant pool index.
static void string(bool canAssign)
{
    emitConstant(OBJ_VAL(copyString(parser.previous.start + 1, parser.previous.length - 2)));
}

// Compiles variable lookups by adding the name to constants table and emitting byte-code
static void namedVariable(Token name, bool canAssign)
{
    // Store the get and set operations associated with the variable being used.
    uint8_t getOp, setOp;
    // Look for a local variable with this name in the current compiler scopes.
    int arg = resolveLocal(current, &name);

    // If the variable is found in the local scope array (resolveLocal returns an index other than -1),
    // configure the compiler to use stack-based local variable op-codes instead of global ones.
    if (arg != -1)
    {
        getOp = OP_GET_LOCAL;
        setOp = OP_SET_LOCAL;
    }
    else
    {
        // Otherwise, treat it as a global variable: store the name in the constant table and use global op-codes.
        arg = identifierConstant(&name);
        getOp = OP_GET_GLOBAL;
        setOp = OP_SET_GLOBAL;
    }

    // Emit instruction to fetch the global variable value at that index. If we match an `=` then we know an assignment is taking place and we must evaluate
    // The expression being assigned to, instead of accessing a global variable. On the LHS of the `=`.
    if (canAssign && match(TOKEN_EQUAL))
    {
        expression();
        emitBytes(setOp, (uint8_t)arg);
    }
    else
    {
        emitBytes(getOp, arg);
    }
}

// Pratt parser callback triggered when an identifier is met as an expression
static void variable(bool canAssign)
{
    // Process the identifier token that was just consumed
    namedVariable(parser.previous, canAssign);
}

// Parse a unary expression (such as !a, -a).
static void unary(bool canAssign)
{
    TokenType operatorType = parser.previous.type;

    // Compile the operand and add it to the chunk of bytecode. We do this before writing the byte-code for the operator due to order of operations.
    // I.e. -a means we need to load a, then negate it and push the result back onto the VM stack.
    parsePrecedence(PREC_UNARY);

    // Emit the operator instruction and add it to the compiled byte-code.
    switch (operatorType)
    {
        case TOKEN_BANG: emitByte(OP_NOT); break;
        case TOKEN_MINUS: emitByte(OP_NEGATE); break;
        default: return; // Unreachable.
    }
}

// A global dispatch table that pairs every distinct token type with its corresponding compilation functions and precedence level.
// We use C's designated array initialiser syntax ('[INDEX] = ...') to explicitly map each 'TokenType' enum value to its exact slot
// within the rules matrix, ensuring clean lookup tracking for the Pratt parser.
ParseRule rules[] = {
  [TOKEN_LEFT_PAREN]    = {grouping, NULL,   PREC_NONE},   // Starts a grouped expression (e.g., '(1 + 2)'). Has no infix role or intrinsic precedence.
  [TOKEN_RIGHT_PAREN]   = {NULL,     NULL,   PREC_NONE},   // Delimits grouping boundaries. Handled manually inside the grouping function.
  [TOKEN_LEFT_BRACE]    = {NULL,     NULL,   PREC_NONE},   // Delimits block structures. Handled separately by statement parsers.
  [TOKEN_RIGHT_BRACE]   = {NULL,     NULL,   PREC_NONE},   // Delimits block structures. Handled separately by statement parsers.
  [TOKEN_COMMA]         = {NULL,     NULL,   PREC_NONE},   // Delimits arguments and parameters. Evaluated explicitly in call expressions.
  [TOKEN_DOT]           = {NULL,     NULL,   PREC_NONE},   // Delimits property access. Will act as an infix operator later.
  [TOKEN_MINUS]         = {unary,    binary, PREC_TERM},   // Dual-role token: acts as prefix negation ('-a') or infix subtraction ('a - b') at addition level.
  [TOKEN_PLUS]          = {NULL,     binary, PREC_TERM},   // Acts strictly as an infix addition operator ('a + b') at the term level.
  [TOKEN_SEMICOLON]     = {NULL,     NULL,   PREC_NONE},   // Statement terminator token. Delimits execution bounds rather than producing values.
  [TOKEN_SLASH]         = {NULL,     binary, PREC_FACTOR}, // Acts strictly as an infix division operator ('a / b') at multiplication level.
  [TOKEN_STAR]          = {NULL,     binary, PREC_FACTOR}, // Acts strictly as an infix multiplication operator ('a * b') at multiplication level.
  [TOKEN_BANG]          = {unary,    NULL,   PREC_NONE},   // Prefix logical negation operator ('!a'). Covered fully in a later section.
  [TOKEN_BANG_EQUAL]    = {NULL,     binary, PREC_EQUALITY},   // Infix structural inequality operator ('a != b'). Covered fully in a later section.
  [TOKEN_EQUAL]         = {NULL,     NULL,   PREC_NONE},   // Variable assignment operator ('a = b'). Evaluated safely below equality levels.
  [TOKEN_EQUAL_EQUAL]   = {NULL,     binary, PREC_EQUALITY},   // Infix structural equality operator ('a == b'). Covered fully in a later section.
  [TOKEN_GREATER]       = {NULL,     binary, PREC_COMPARISON},   // Infix relational comparison operator ('a > b'). Covered fully in a later section.
  [TOKEN_GREATER_EQUAL] = {NULL,     binary, PREC_COMPARISON},   // Infix relational comparison operator ('a >= b'). Covered fully in a later section.
  [TOKEN_LESS]          = {NULL,     binary, PREC_COMPARISON},   // Infix relational comparison operator ('a < b'). Covered fully in a later section.
  [TOKEN_LESS_EQUAL]    = {NULL,     binary, PREC_COMPARISON},   // Infix relational comparison operator ('a <= b'). Covered fully in a later section.
  [TOKEN_IDENTIFIER]    = {variable, NULL,   PREC_NONE},   // Variable lookups and targets. Will act as a prefix literal loader.
  [TOKEN_STRING]        = {string,   NULL,   PREC_NONE},   // Raw character sequence data literal. Will act as a prefix literal loader.
  [TOKEN_NUMBER]        = {number,   NULL,   PREC_NONE},   // Numeric data literal (e.g., '3.14'). Emits raw values immediately via prefix.
  [TOKEN_AND]           = {NULL,     NULL,   PREC_NONE},   // Logical short-circuiting conjunction operator ('a and b').
  [TOKEN_CLASS]         = {NULL,     NULL,   PREC_NONE},   // Keyword introducing object blueprint descriptions. Handled as a declaration statement.
  [TOKEN_ELSE]          = {NULL,     NULL,   PREC_NONE},   // Keyword splitting conditional statement logical execution flows.
  [TOKEN_FALSE]         = {literal,  NULL,   PREC_NONE},   // Boolean false data literal. Will act as a prefix literal loader.
  [TOKEN_FOR]           = {NULL,     NULL,   PREC_NONE},   // Keyword introducing basic entry iterative control structures.
  [TOKEN_FUN]           = {NULL,     NULL,   PREC_NONE},   // Keyword introducing local subroutine declarations.
  [TOKEN_IF]            = {NULL,     NULL,   PREC_NONE},   // Keyword introducing basic branching conditional execution flows.
  [TOKEN_NIL]           = {literal,  NULL,   PREC_NONE},   // Clear representation of null/empty data references.
  [TOKEN_OR]            = {NULL,     NULL,   PREC_NONE},   // Logical short-circuiting disjunction operator ('a or b').
  [TOKEN_PRINT]         = {NULL,     NULL,   PREC_NONE},   // Statement keyword outputting evaluation results straight to stdout.
  [TOKEN_RETURN]        = {NULL,     NULL,   PREC_NONE},   // Statement keyword exiting active frames, optionally tracking output variables.
  [TOKEN_SUPER]         = {NULL,     NULL,   PREC_NONE},   // References base implementation contexts during class inheritance lookups.
  [TOKEN_THIS]          = {NULL,     NULL,   PREC_NONE},   // References local instantiation contexts during instance method lookups.
  [TOKEN_TRUE]          = {literal,  NULL,   PREC_NONE},   // Boolean true data literal. Will act as a prefix literal loader.
  [TOKEN_VAR]           = {NULL,     NULL,   PREC_NONE},   // Statement keyword declaring new mutable data spaces within local scope.
  [TOKEN_WHILE]         = {NULL,     NULL,   PREC_NONE},   // Keyword introducing basic truth-dependent looping control structures.
  [TOKEN_ERROR]         = {NULL,     NULL,   PREC_NONE},   // Synthetic placeholder token dispatched to signal lexing anomalies safely.
  [TOKEN_EOF]           = {NULL,     NULL,   PREC_NONE},   // Structural sentinel tracking termination of source file instruction scanning.
};

// Parses and compiles expressions at or above a given operator precedence level.
static void parsePrecedence(Precedence precedence)
{
    advance();
     // Retrieve the prefix compilation function pointer associated with the token just consumed.
    ParseFn prefixRule = getRule(parser.previous.type) -> prefix;
    // If the token cannot legally start an expression (no prefix rule exists), flag a compilation error.
    if (prefixRule == NULL)
    {
        error("Expect expression.");
        return;
    }
    // Execute the prefix function to compile the leading component of the expression (e.g., a literal or unary op). Ensuring that precedence with equals is handled properly.
    bool canAssign = precedence <= PREC_ASSIGNMENT;
    prefixRule(canAssign);

    // Keep consuming tokens as long as the incoming operator's precedence meets or exceeds
    // the minimum required precedence parameter level. This binds matching higher-priority operations first.
    while (precedence <= getRule(parser.current.type) -> precedence)
    {
        advance();
        // Fetch the infix compilation function pointer matched to the operator token.
        ParseFn infixRule = getRule(parser.previous.type) -> infix;
        // Execute the infix function (e.g., binary()) to consume the right-hand operand and emit the operation bytecode.
        infixRule(canAssign);
    }

    if (canAssign && match(TOKEN_EQUAL))
    {
        error("Invalid assignment target.");
    }
}

// Adds a variable's name string to the constant pool and returns its index.
static uint8_t identifierConstant(Token* name)
{
    // 1. copyString: Creates a new heap-allocated ObjString from the token text.
    // 2. OBJ_VAL: Wraps that ObjString pointer into a clox Value type.
    // 3. makeConstant: Inserts the Value into the chunk's constant array.
    return makeConstant(OBJ_VAL(copyString(name -> start, name -> length)));
}

// Check that two identifiers are the same.
static bool identifiersEqual(Token* a, Token* b)
{
    if (a -> length != b -> length) return false;
    return memcmp(a -> start, b -> start, a -> length) == 0;
}

// Look up a variable to determine if it is currently in local scope.
static int resolveLocal(Compiler* compiler, Token* name)
{
    // Loop backwards through the locals array to search from the innermost scope outwards.
    // This ensures that variables in inner scopes correctly shadow variables with the same name in outer scopes.
    for (int i = compiler->localCount - 1; i >= 0; i--)
    {
        // Get a pointer to the local variable currently being evaluated in the array.
        Local* local = &compiler->locals[i];

        // Check if the identifier token name matches the name of the tracked local variable.
        if (identifiersEqual(name, &local->name))
        {
            // Ensure that the variable has been fully defined. Return a compiler error if it is not.
            if (local -> depth == -1)
            {
                error("Can't read local variable in its own initializer.");
            }

            // Return the stack slot index where this local variable resides at runtime.
            return i;
        }
    }

    // Return -1 if no local variable with a matching name is found, signaling it may be a global.
    return -1;
}


// Add a local variable to the compilers' locals list. Record the current depth of the compiler to be able to find the correct
// offset within the stack, when accessing the local variable.
static void addLocal(Token name)
{
    // Ensure that we space to define a local variable. As the VM can only keep track of 256 local variables in scope at any one time.
    if (current -> localCount == UINT8_COUNT)
    {
        error("Too many local variables in function.");
        return;
    }

    Local* local = &current -> locals[current -> localCount++];
    local -> name = name;
    // Set depth to -1 to avoid edges cases such as var a = a;
    local -> depth = -1;
}

// Function to declare a local variable. We do not consider globals in the same way as local variables are already stored on the stack,
// and therefore stack offsets can be used to improve performance.
static void declareVariable()
{
    // Global variables are not tracked by the compiler's local array, so exit early if at scope depth 0.
    if (current -> scopeDepth == 0) return;

    // Grab a pointer to the identifier token that was just parsed to use as the variable's name.
    Token* name = &parser.previous;

    // Ensure that a variable cannot be declared with the same name and scope level. Due to creating ambiguity in the compiler.
    // We count backwards because localCount points to the last declared variable. Therefore all previously declared variables are at indices [0..localCount].
    // We can consider all variables currently declared (and therefore have any chance of being in scope) by checking all locals before the one being declared.
    for (int i = current -> localCount - 1; i >= 0; i--)
    {
        Local* local = &current -> locals[i];
        if (local -> depth != -1 && local -> depth < current -> scopeDepth)
        {
            break;
        }

        if (identifiersEqual(name, &local -> name))
        {
            error("Already a variable with this name in this scope.");
        }
    }

    // Append the variable to the compiler's tracking array, marking it as a new local in the current scope.
    addLocal(*name);
}

// Ensures the next token is an identifier and registers its name as a constant.
static uint8_t parseVariable(const char* errorMessage)
{
    consume(TOKEN_IDENTIFIER, errorMessage);

    // Declares the variable to the compiler, tracking it within the locals array if inside a block.
    declareVariable();
    // If the variable is local (scope depth > 0), return a dummy index of 0. Local variables
    // do not store their string names in the constant pool because they are resolved via stack offsets.
    if (current -> scopeDepth > 0)
    {
        markInitialized();
        return 0;
    }


    // Sends the just-consumed identifier token to be stored in the constant pool.
    return identifierConstant(&parser.previous);
}

static void markInitialized()
{
    current -> locals[current -> localCount - 1].depth = current -> scopeDepth;
}

static void defineVariable(uint8_t global)
{
    if (current -> scopeDepth > 0)
    {
        return;
    }
    emitBytes(OP_DEFINE_GLOBAL, global);
}

// Fetch a parsing rule for the Pratt parser based off of type.
static ParseRule* getRule(TokenType type)
{
    return &rules[type];
}

// Scan and compile Lox source code and produce a chunk of byte-code to be used by the virtual machine.
bool compile(const char* source, Chunk* chunk)
{
    initScanner(source);
    Compiler compiler;
    initCompiler(&compiler);

    // Chunk to create with the compiler = the chunk within the VM to be filled and is hence empty.
    compilingChunk = chunk;

    // Initialise error handling flags.
    parser.hadError = false;
    parser.panicMode = false;

    // Ensure next token is a meaningful one.
    advance();

    while (!match(TOKEN_EOF))
    {
        declaration();
    }

    // We have consumed the EOF token and hence the compiler has produced the required byte-code chunk and can hence be terminated.
    endCompiler();
    return !parser.hadError;
}
